### ISSUE TITLE
What is the purpose of `vl`?

### ISSUE THREAD

**Issue by eblume** [nmasur/dotfiles#74]
Hi @nmasur , I hope you are well! I have another question about your config.

What is the purpose of [this `vl` alias?](https://github.com/nmasur/dotfiles/blob/4ca25aa1947e172748f17fbf711ac1df91421cd9/modules/common/neovim/default.nix#L46)

    nvim -c 'normal! `0' -c 'bdelete 1'

I understand (I think) that "nvim -c 'normal! \`0'" means "open vim to the last edited position", which is cool enough. What does  `bdelete 1` mean here though? I understand from `:help bdelete` that it's something to do with closing an open buffer, but from my own testing I seem to generally not be working in buffers starting from 1 - it's actually kind of curious, I haven't ever had much cause to work with `:ls` in vim and so I hadn't noticed the behavior before but it seems to retain old cached buffer numbers for files, is this related to the way you [set up nvim backup and swap](https://github.com/nmasur/dotfiles/blob/4ca25aa1947e172748f17fbf711ac1df91421cd9/modules/common/neovim/config/misc.nix#L58-L63)?

Thanks again!

**Comment by nmasur** [comment]
Hey @eblume,

This is a quirky one, and I think it's due to the fact that I have the [bufferline.nvim](https://github.com/akinsho/bufferline.nvim) plugin installed, which shows buffers as a tab bar at the top of the Neovim window.

Whenever I open Neovim, it defaults to an empty buffer. With the ``-c 'normal! `0'`` command it will then jump to the last edited position of the most recent file, but it will leave open the empty buffer as `[No Name]`:

<img width="563" alt="Screenshot 2024-07-10 at 9 48 41 AM" src="https://github.com/nmasur/dotfiles/assets/7386960/e6793e46-9b18-4639-a634-3de9782e834f">

So by adding `-c 'bdelete 1'`, we kill the first empty buffer and only get the file we want.

**Comment by eblume** [comment]
Thanks, that explains it! I've disabled bufferline in my build, so I don't even see the other buffer being left 'open'.

Appreciated as always!
